# File: templates/npm-with-params.yml

parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  path: ''
  project: ''
  dotnetVersion: ''
  
jobs:
  - job: ${{ parameters.name }}
    displayName: Test.Unit
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      buildConfiguration: 'Debug'
    steps:
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: |
            test/${{ parameters.path }}/${{ parameters.projects }}
      - script: "dotnet test 'test/${{ parameters.path }}/${{ parameters.projects }}' --configuration debug --collect:'XPlat Code Coverage'"
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: 'test/${{ parameters.path }}/TestResults/**/coverage.cobertura.xml'
