# File: templates/npm-with-params.yml

parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  extension: 'fsproj'
  dotnetVersion: ''
  
jobs:
  - job: run_unit_test
    displayName: Test.Unit
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: 'Debug'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: ${{ parameters.dotnetVersion }}
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: |
          test/RedRabbit.UnitTest/*.${{ parameters.extension }}
        arguments: '--configuration debug'
