# File: templates/npm-with-params.yml

parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  extension: 'fsproj'
  dotnetVersion: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: Test.Unit
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      buildConfiguration: 'Debug'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: ${{ parameters.dotnetVersion }}
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: |
          test/${{ parameters.name }}/*.${{ parameters.extension }}
        arguments: '--configuration debug'
